[package]
name = "cfd-rs"
authors = ["Xavier N."]
version = "0.1.0"
edition = "2021"
description = "A lib for computing fluid dynamics, using finite volume method (WIP)."
license = "MIT OR Apache-2.0"

[dependencies]
